---
title: Dressipi.com
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  downloads:
    title: Downloads
    output: true
  jobs:
    title: Jobs
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: downloads
  values:
    permalink: "/downloads/:title/"
    form:
      title: Download Now
      button: Download Case Study
      file: 
    testimonial:
      body: 
      logo: 
      author:
        name: 
        job-title: 
        company: 
        image: 
      action: Download Now
    layout: download
- scope:
    path: ''
    type: clients
  values:
    logo: 
    link: 
- scope:
    path: ''
    type: pages
  values:
    navigation: 
    header:
      title: 
      body: 
      button:
        copy: 
        url: 
      hero-image: 
    include-form-demo: false
    layout: page
- scope:
    path: ''
    type: jobs
  values:
    is-open: true
description: Personalising the Entire Customer Experience
url: http://www.dressipi.com
form-demo:
  formspree-ID: xojeeoem
  title: Achieve Great Results For Your Business With Dressipi
  subtitle: Schedule a demo to see how Dressipi can help increase net incremental
    revenue per visitor, AOV and frequency of purchase.
  button: Book a Demo
  email_cc: 
  redirect: "/thanks"
company:
  name: Stylemania Ltd.
  address:
    street: 20 Eastbourne Terrace
    city: London W2 6LG
twitter:
  username: dressipi
social:
  links:
  - name: Twitter
    link: https://www.twitter.com/dressipi
  - name: Instagram
    link: https://www.instagram.com/dressipi
  - name: LinkedIn
    link: https://www.linkedin.com/company/dressipi
gtm-code: GTM-TRK2KPX
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- ".gitignore"
plugins_dir:
- jekyll-sitemap
# - jekyll-seo-tag
